name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest in prod checkout
        run: git -C /Users/munyinsam/Prod/csp/BangkokTOR-frontend pull --ff-only

      - name: Docker compose up
        run: docker compose up -d --build
        working-directory: /Users/munyinsam/Prod/csp/BangkokTOR-frontend
